// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as v1 from './v1';
import {ImageAnnotatorClient, ProductSearchClient} from './v1';
import * as v1p1beta1 from './v1p1beta1';
import * as v1p2beta1 from './v1p2beta1';
import * as v1p3beta1 from './v1p3beta1';
import * as v1p4beta1 from './v1p4beta1';
import * as helpers from './helpers';

const gapic: any = Object.freeze({
  v1: v1,
  v1p1beta1: v1p1beta1,
  v1p2beta1: v1p2beta1,
  v1p3beta1: v1p3beta1,
  v1p4beta1: v1p4beta1,
});

// Augment the ImageAnnotatorClient objects with the helpers.
for (const gapicVersion of Object.keys(gapic)) {
  const clientProto = gapic[gapicVersion].ImageAnnotatorClient.prototype;
  Object.assign(clientProto, helpers.call(gapicVersion));
}

module.exports = gapic.v1;
module.exports.v1 = gapic.v1;
module.exports.v1p1beta1 = gapic.v1p1beta1;
module.exports.v1p2beta1 = gapic.v1p2beta1;
module.exports.v1p3beta1 = gapic.v1p3beta1;
module.exports.v1p4beta1 = gapic.v1p4beta1;
module.exports.default = Object.assign({}, module.exports);
export {ImageAnnotatorClient, ProductSearchClient};
